# Generated by Django 5.0.3 on 2024-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email_address',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
    ]
