# Generated by Django 5.0.3 on 2024-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, max_length=300, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'контакты клиента',
                'verbose_name_plural': 'контакты клиента',
            },
        ),
    ]
