# Generated by Django 5.0.3 on 2024-04-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DateTimeField(blank=True, null=True, verbose_name='окончание регистрации')),
                ('name', models.CharField(max_length=150, verbose_name='номер гос. регистрации')),
                ('is_current', models.BooleanField(default=True, verbose_name='актуальная')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
