# Generated by Django 5.0.3 on 2024-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
